"""
Tests for POST /api/upload: validation (type, extension, size, empty) and success (mocked pipeline).
"""
import uuid
from unittest.mock import MagicMock, patch

import pytest
from fastapi.testclient import TestClient

from app.models.document import DocumentStatus, create_indexing_result

# Minimal valid PDF (single page, empty content) - PDF header + minimal structure
MINIMAL_PDF_BYTES = b"""%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj
xref
0 4
0000000000 65535 f
0000000009 00000 n
0000000052 00000 n
0000000101 00000 n
trailer<</Size 4/Root 1 0 R>>
startxref
178
%%EOF"""


@pytest.fixture
def mock_indexing_result():
    """Fake IndexingResult for successful upload."""
    return create_indexing_result(
        doc_id="test-doc-uuid",
        name="sample.pdf",
        chunks_count=5,
        status=DocumentStatus.COMPLETED,
        processing_time=0.1,
        warnings=[],
    )


def test_upload_rejects_non_pdf_content_type(client: TestClient) -> None:
    """400 when Content-Type is not application/pdf."""
    response = client.post(
        "/api/upload",
        files={"file": ("doc.pdf", b"fake content", "text/plain")},
    )
    assert response.status_code == 400
    assert response.json().get("detail", "") == "Chi chap nhan file PDF."


def test_upload_rejects_wrong_extension(client: TestClient) -> None:
    """400 when filename does not end with .pdf."""
    response = client.post(
        "/api/upload",
        files={"file": ("document.txt", MINIMAL_PDF_BYTES, "application/pdf")},
    )
    assert response.status_code == 400
    assert response.json().get("detail", "") == "File tải lên phải có đuôi .pdf."


def test_upload_rejects_empty_file(client: TestClient) -> None:
    """400 when file content is empty."""
    response = client.post(
        "/api/upload",
        files={"file": ("empty.pdf", b"", "application/pdf")},
    )
    assert response.status_code == 400
    assert response.json().get("detail", "") == "File tải lên đang rỗng."


@patch("app.routers.upload.get_config")
def test_upload_rejects_file_too_large(mock_get_config, client: TestClient) -> None:
    """413 when file size exceeds limit."""
    cfg = MagicMock()
    cfg.upload_max_size_mb = 0
    cfg.upload_allowed_content_types = ("application/pdf",)
    mock_get_config.return_value = cfg

    response = client.post(
        "/api/upload",
        files={"file": ("large.pdf", b"x" * 11, "application/pdf")},
    )
    assert response.status_code == 413
    assert response.json().get("detail", "") == "File vượt quá giới hạn 0 MB."


@patch("app.routers.upload.run_indexing_pipeline_from_upload")
def test_upload_success_returns_doc_id_and_chunks(
    mock_pipeline,
    client: TestClient,
    mock_indexing_result,
) -> None:
    """200 and response with doc_id, chunks_count when pipeline succeeds."""
    mock_pipeline.return_value = mock_indexing_result
    response = client.post(
        "/api/upload",
        files={"file": ("sample.pdf", MINIMAL_PDF_BYTES, "application/pdf")},
    )
    assert response.status_code == 200
    data = response.json()
    assert data["doc_id"] == "test-doc-uuid"
    assert data["chunks_count"] == 5
    mock_pipeline.assert_called_once()
    call_args = mock_pipeline.call_args[0]
    assert call_args[0] == MINIMAL_PDF_BYTES
    assert call_args[1] == "sample.pdf"
    # doc_id is generated by router before calling pipeline
    assert isinstance(call_args[2], str)
    uuid.UUID(call_args[2])


@patch("app.routers.upload.run_indexing_pipeline_from_upload")
def test_upload_includes_warnings_in_response(
    mock_pipeline,
    client: TestClient,
) -> None:
    """Response includes pipeline warnings when present."""
    mock_pipeline.return_value = create_indexing_result(
        doc_id="warn-doc",
        name="scan.pdf",
        chunks_count=2,
        status=DocumentStatus.COMPLETED,
        processing_time=0.1,
        warnings=["Possible scanned PDF."],
    )
    response = client.post(
        "/api/upload",
        files={"file": ("scan.pdf", MINIMAL_PDF_BYTES, "application/pdf")},
    )
    assert response.status_code == 200
    body = response.json()
    assert "Possible scanned PDF" in str(body.get("warnings", []))


@patch("app.routers.upload.run_indexing_pipeline_from_upload")
def test_upload_400_on_indexing_value_error(
    mock_pipeline,
    client: TestClient,
) -> None:
    """400 when pipeline raises ValueError (e.g. corrupt PDF)."""
    mock_pipeline.side_effect = ValueError("PDF file is corrupt or unreadable")
    response = client.post(
        "/api/upload",
        files={"file": ("bad.pdf", MINIMAL_PDF_BYTES, "application/pdf")},
    )
    assert response.status_code == 400
    assert response.json().get("detail", "") == "File PDF bị hỏng hoặc không đọc được."


@patch("app.routers.upload.run_indexing_pipeline_from_upload")
def test_upload_500_on_indexing_exception(
    mock_pipeline,
    client: TestClient,
) -> None:
    """500 when pipeline raises generic Exception, without leaking internal details."""
    mock_pipeline.side_effect = RuntimeError("Milvus connection failed")
    response = client.post(
        "/api/upload",
        files={"file": ("x.pdf", MINIMAL_PDF_BYTES, "application/pdf")},
    )
    assert response.status_code == 500
    detail = response.json().get("detail", "")
    assert "Không thể xử lý file PDF" in detail
    assert "Milvus" not in detail
